version: '3.8'

services:
  
  api:
    build: ./app
    ports:
      - "8000:8000"  
    depends_on:
      - db  
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://mi_usuario:mi_password@db:5432/inventario_db

  
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=mi_usuario
      - POSTGRES_PASSWORD=mi_password
      - POSTGRES_DB=inventario_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Definici√≥n del volumen persistente
volumes:
  postgres_data: